#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Land.DBContext
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Land")]
	public partial class DBLandDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertStreetDetail(StreetDetail instance);
    partial void UpdateStreetDetail(StreetDetail instance);
    partial void DeleteStreetDetail(StreetDetail instance);
    partial void InsertStreet(Street instance);
    partial void UpdateStreet(Street instance);
    partial void DeleteStreet(Street instance);
    partial void InsertDefinition(Definition instance);
    partial void UpdateDefinition(Definition instance);
    partial void DeleteDefinition(Definition instance);
    partial void InsertDefinitionGroup(DefinitionGroup instance);
    partial void UpdateDefinitionGroup(DefinitionGroup instance);
    partial void DeleteDefinitionGroup(DefinitionGroup instance);
    partial void InsertLand(Land instance);
    partial void UpdateLand(Land instance);
    partial void DeleteLand(Land instance);
    #endregion
		
		public DBLandDataContext() : 
				base(global::Land.Properties.Settings.Default.LandConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DBLandDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLandDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLandDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBLandDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StreetDetail> StreetDetails
		{
			get
			{
				return this.GetTable<StreetDetail>();
			}
		}
		
		public System.Data.Linq.Table<Street> Streets
		{
			get
			{
				return this.GetTable<Street>();
			}
		}
		
		public System.Data.Linq.Table<VTax> VTaxes
		{
			get
			{
				return this.GetTable<VTax>();
			}
		}
		
		public System.Data.Linq.Table<vDefinition> vDefinitions
		{
			get
			{
				return this.GetTable<vDefinition>();
			}
		}
		
		public System.Data.Linq.Table<Definition> Definitions
		{
			get
			{
				return this.GetTable<Definition>();
			}
		}
		
		public System.Data.Linq.Table<DefinitionGroup> DefinitionGroups
		{
			get
			{
				return this.GetTable<DefinitionGroup>();
			}
		}
		
		public System.Data.Linq.Table<Land> Lands
		{
			get
			{
				return this.GetTable<Land>();
			}
		}
		
		public System.Data.Linq.Table<VLand> VLands
		{
			get
			{
				return this.GetTable<VLand>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StreetDetail")]
	public partial class StreetDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _StreetId;
		
		private System.Nullable<int> _FromId;
		
		private System.Nullable<int> _ToId;
		
		private System.Nullable<decimal> _Price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStreetIdChanging(System.Nullable<int> value);
    partial void OnStreetIdChanged();
    partial void OnFromIdChanging(System.Nullable<int> value);
    partial void OnFromIdChanged();
    partial void OnToIdChanging(System.Nullable<int> value);
    partial void OnToIdChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    #endregion
		
		public StreetDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetId", DbType="Int")]
		public System.Nullable<int> StreetId
		{
			get
			{
				return this._StreetId;
			}
			set
			{
				if ((this._StreetId != value))
				{
					this.OnStreetIdChanging(value);
					this.SendPropertyChanging();
					this._StreetId = value;
					this.SendPropertyChanged("StreetId");
					this.OnStreetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FromId", DbType="Int")]
		public System.Nullable<int> FromId
		{
			get
			{
				return this._FromId;
			}
			set
			{
				if ((this._FromId != value))
				{
					this.OnFromIdChanging(value);
					this.SendPropertyChanging();
					this._FromId = value;
					this.SendPropertyChanged("FromId");
					this.OnFromIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToId", DbType="Int")]
		public System.Nullable<int> ToId
		{
			get
			{
				return this._ToId;
			}
			set
			{
				if ((this._ToId != value))
				{
					this.OnToIdChanging(value);
					this.SendPropertyChanging();
					this._ToId = value;
					this.SendPropertyChanged("ToId");
					this.OnToIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Street")]
	public partial class Street : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<int> _DistrictId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnDistrictIdChanging(System.Nullable<int> value);
    partial void OnDistrictIdChanged();
    #endregion
		
		public Street()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictId", DbType="Int")]
		public System.Nullable<int> DistrictId
		{
			get
			{
				return this._DistrictId;
			}
			set
			{
				if ((this._DistrictId != value))
				{
					this.OnDistrictIdChanging(value);
					this.SendPropertyChanging();
					this._DistrictId = value;
					this.SendPropertyChanged("DistrictId");
					this.OnDistrictIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VTax")]
	public partial class VTax
	{
		
		private int _Id;
		
		private string _Name;
		
		private System.Nullable<decimal> _Price;
		
		private string _StreetFrom;
		
		private string _StreetTo;
		
		private System.Nullable<decimal> _Price1;
		
		private System.Nullable<int> _DistrictId;
		
		private string _District;
		
		public VTax()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetFrom", DbType="NVarChar(500)")]
		public string StreetFrom
		{
			get
			{
				return this._StreetFrom;
			}
			set
			{
				if ((this._StreetFrom != value))
				{
					this._StreetFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetTo", DbType="NVarChar(500)")]
		public string StreetTo
		{
			get
			{
				return this._StreetTo;
			}
			set
			{
				if ((this._StreetTo != value))
				{
					this._StreetTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price1", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Price1
		{
			get
			{
				return this._Price1;
			}
			set
			{
				if ((this._Price1 != value))
				{
					this._Price1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictId", DbType="Int")]
		public System.Nullable<int> DistrictId
		{
			get
			{
				return this._DistrictId;
			}
			set
			{
				if ((this._DistrictId != value))
				{
					this._DistrictId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="NVarChar(100)")]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this._District = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vDefinition")]
	public partial class vDefinition
	{
		
		private int _Id;
		
		private System.Nullable<int> _GroupId;
		
		private string _DefGroup;
		
		private string _Code;
		
		private string _Name;
		
		public vDefinition()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int")]
		public System.Nullable<int> GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this._GroupId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefGroup", DbType="NVarChar(50)")]
		public string DefGroup
		{
			get
			{
				return this._DefGroup;
			}
			set
			{
				if ((this._DefGroup != value))
				{
					this._DefGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(100)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Definition")]
	public partial class Definition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Code;
		
		private string _Name;
		
		private System.Nullable<int> _GroupId;
		
		private string _Description;
		
		private System.Nullable<bool> _Bit;
		
		private System.Nullable<int> _UserId;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _Num1;
		
		private System.Nullable<int> _Num2;
		
		private System.Nullable<decimal> _Capacity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnGroupIdChanging(System.Nullable<int> value);
    partial void OnGroupIdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnBitChanging(System.Nullable<bool> value);
    partial void OnBitChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnNum1Changing(System.Nullable<int> value);
    partial void OnNum1Changed();
    partial void OnNum2Changing(System.Nullable<int> value);
    partial void OnNum2Changed();
    partial void OnCapacityChanging(System.Nullable<decimal> value);
    partial void OnCapacityChanged();
    #endregion
		
		public Definition()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(100)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int")]
		public System.Nullable<int> GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this.OnGroupIdChanging(value);
					this.SendPropertyChanging();
					this._GroupId = value;
					this.SendPropertyChanged("GroupId");
					this.OnGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bit", DbType="Bit")]
		public System.Nullable<bool> Bit
		{
			get
			{
				return this._Bit;
			}
			set
			{
				if ((this._Bit != value))
				{
					this.OnBitChanging(value);
					this.SendPropertyChanging();
					this._Bit = value;
					this.SendPropertyChanged("Bit");
					this.OnBitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num1", DbType="Int")]
		public System.Nullable<int> Num1
		{
			get
			{
				return this._Num1;
			}
			set
			{
				if ((this._Num1 != value))
				{
					this.OnNum1Changing(value);
					this.SendPropertyChanging();
					this._Num1 = value;
					this.SendPropertyChanged("Num1");
					this.OnNum1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num2", DbType="Int")]
		public System.Nullable<int> Num2
		{
			get
			{
				return this._Num2;
			}
			set
			{
				if ((this._Num2 != value))
				{
					this.OnNum2Changing(value);
					this.SendPropertyChanging();
					this._Num2 = value;
					this.SendPropertyChanged("Num2");
					this.OnNum2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				if ((this._Capacity != value))
				{
					this.OnCapacityChanging(value);
					this.SendPropertyChanging();
					this._Capacity = value;
					this.SendPropertyChanged("Capacity");
					this.OnCapacityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DefinitionGroup")]
	public partial class DefinitionGroup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _DefGroup;
		
		private string _Description;
		
		private System.Nullable<int> _First;
		
		private System.Nullable<int> _Last;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDefGroupChanging(string value);
    partial void OnDefGroupChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnFirstChanging(System.Nullable<int> value);
    partial void OnFirstChanged();
    partial void OnLastChanging(System.Nullable<int> value);
    partial void OnLastChanged();
    #endregion
		
		public DefinitionGroup()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefGroup", DbType="NVarChar(50)")]
		public string DefGroup
		{
			get
			{
				return this._DefGroup;
			}
			set
			{
				if ((this._DefGroup != value))
				{
					this.OnDefGroupChanging(value);
					this.SendPropertyChanging();
					this._DefGroup = value;
					this.SendPropertyChanged("DefGroup");
					this.OnDefGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(200)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First", DbType="Int")]
		public System.Nullable<int> First
		{
			get
			{
				return this._First;
			}
			set
			{
				if ((this._First != value))
				{
					this.OnFirstChanging(value);
					this.SendPropertyChanging();
					this._First = value;
					this.SendPropertyChanged("First");
					this.OnFirstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last", DbType="Int")]
		public System.Nullable<int> Last
		{
			get
			{
				return this._Last;
			}
			set
			{
				if ((this._Last != value))
				{
					this.OnLastChanging(value);
					this.SendPropertyChanging();
					this._Last = value;
					this.SendPropertyChanged("Last");
					this.OnLastChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Land")]
	public partial class Land : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Title;
		
		private string _Address;
		
		private System.Nullable<int> _StreetId;
		
		private System.Nullable<int> _DistrictId;
		
		private System.Nullable<int> _WardId;
		
		private System.Nullable<decimal> _AlleyWide;
		
		private string _Contact;
		
		private string _Phone;
		
		private System.Nullable<bool> _IsAgent;
		
		private System.Nullable<bool> _IsDue;
		
		private string _Comment;
		
		private System.Nullable<decimal> _Area;
		
		private System.Nullable<decimal> _Wide;
		
		private System.Nullable<decimal> _Length;
		
		private System.Nullable<int> _DirectionId;
		
		private System.Nullable<bool> _IsHouse;
		
		private System.Nullable<int> _HouseLevel;
		
		private System.Nullable<int> _Bedroom;
		
		private System.Nullable<int> _Restroom;
		
		private System.Nullable<int> _Floor;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<decimal> _AgentPrice;
		
		private System.Nullable<decimal> _ExpectedPrice;
		
		private string _Url;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<decimal> _Tax;
		
		private System.Nullable<bool> _IsMezzanine;
		
		private System.Nullable<bool> _IsSale;
		
		private System.Nullable<decimal> _PricePerMet;
		
		private System.Nullable<bool> _IsDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnStreetIdChanging(System.Nullable<int> value);
    partial void OnStreetIdChanged();
    partial void OnDistrictIdChanging(System.Nullable<int> value);
    partial void OnDistrictIdChanged();
    partial void OnWardIdChanging(System.Nullable<int> value);
    partial void OnWardIdChanged();
    partial void OnAlleyWideChanging(System.Nullable<decimal> value);
    partial void OnAlleyWideChanged();
    partial void OnContactChanging(string value);
    partial void OnContactChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnIsAgentChanging(System.Nullable<bool> value);
    partial void OnIsAgentChanged();
    partial void OnIsDueChanging(System.Nullable<bool> value);
    partial void OnIsDueChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnAreaChanging(System.Nullable<decimal> value);
    partial void OnAreaChanged();
    partial void OnWideChanging(System.Nullable<decimal> value);
    partial void OnWideChanged();
    partial void OnLengthChanging(System.Nullable<decimal> value);
    partial void OnLengthChanged();
    partial void OnDirectionIdChanging(System.Nullable<int> value);
    partial void OnDirectionIdChanged();
    partial void OnIsHouseChanging(System.Nullable<bool> value);
    partial void OnIsHouseChanged();
    partial void OnHouseLevelChanging(System.Nullable<int> value);
    partial void OnHouseLevelChanged();
    partial void OnBedroomChanging(System.Nullable<int> value);
    partial void OnBedroomChanged();
    partial void OnRestroomChanging(System.Nullable<int> value);
    partial void OnRestroomChanged();
    partial void OnFloorChanging(System.Nullable<int> value);
    partial void OnFloorChanged();
    partial void OnPriceChanging(System.Nullable<decimal> value);
    partial void OnPriceChanged();
    partial void OnAgentPriceChanging(System.Nullable<decimal> value);
    partial void OnAgentPriceChanged();
    partial void OnExpectedPriceChanging(System.Nullable<decimal> value);
    partial void OnExpectedPriceChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnTaxChanging(System.Nullable<decimal> value);
    partial void OnTaxChanged();
    partial void OnIsMezzanineChanging(System.Nullable<bool> value);
    partial void OnIsMezzanineChanged();
    partial void OnIsSaleChanging(System.Nullable<bool> value);
    partial void OnIsSaleChanged();
    partial void OnPricePerMetChanging(System.Nullable<decimal> value);
    partial void OnPricePerMetChanged();
    partial void OnIsDetailChanging(System.Nullable<bool> value);
    partial void OnIsDetailChanged();
    #endregion
		
		public Land()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetId", DbType="Int")]
		public System.Nullable<int> StreetId
		{
			get
			{
				return this._StreetId;
			}
			set
			{
				if ((this._StreetId != value))
				{
					this.OnStreetIdChanging(value);
					this.SendPropertyChanging();
					this._StreetId = value;
					this.SendPropertyChanged("StreetId");
					this.OnStreetIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictId", DbType="Int")]
		public System.Nullable<int> DistrictId
		{
			get
			{
				return this._DistrictId;
			}
			set
			{
				if ((this._DistrictId != value))
				{
					this.OnDistrictIdChanging(value);
					this.SendPropertyChanging();
					this._DistrictId = value;
					this.SendPropertyChanged("DistrictId");
					this.OnDistrictIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WardId", DbType="Int")]
		public System.Nullable<int> WardId
		{
			get
			{
				return this._WardId;
			}
			set
			{
				if ((this._WardId != value))
				{
					this.OnWardIdChanging(value);
					this.SendPropertyChanging();
					this._WardId = value;
					this.SendPropertyChanged("WardId");
					this.OnWardIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleyWide", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> AlleyWide
		{
			get
			{
				return this._AlleyWide;
			}
			set
			{
				if ((this._AlleyWide != value))
				{
					this.OnAlleyWideChanging(value);
					this.SendPropertyChanging();
					this._AlleyWide = value;
					this.SendPropertyChanged("AlleyWide");
					this.OnAlleyWideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NVarChar(500)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this.OnContactChanging(value);
					this.SendPropertyChanging();
					this._Contact = value;
					this.SendPropertyChanged("Contact");
					this.OnContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAgent", DbType="Bit")]
		public System.Nullable<bool> IsAgent
		{
			get
			{
				return this._IsAgent;
			}
			set
			{
				if ((this._IsAgent != value))
				{
					this.OnIsAgentChanging(value);
					this.SendPropertyChanging();
					this._IsAgent = value;
					this.SendPropertyChanged("IsAgent");
					this.OnIsAgentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDue", DbType="Bit")]
		public System.Nullable<bool> IsDue
		{
			get
			{
				return this._IsDue;
			}
			set
			{
				if ((this._IsDue != value))
				{
					this.OnIsDueChanging(value);
					this.SendPropertyChanging();
					this._IsDue = value;
					this.SendPropertyChanged("IsDue");
					this.OnIsDueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this.OnAreaChanging(value);
					this.SendPropertyChanging();
					this._Area = value;
					this.SendPropertyChanged("Area");
					this.OnAreaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wide", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Wide
		{
			get
			{
				return this._Wide;
			}
			set
			{
				if ((this._Wide != value))
				{
					this.OnWideChanging(value);
					this.SendPropertyChanging();
					this._Wide = value;
					this.SendPropertyChanged("Wide");
					this.OnWideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				if ((this._Length != value))
				{
					this.OnLengthChanging(value);
					this.SendPropertyChanging();
					this._Length = value;
					this.SendPropertyChanged("Length");
					this.OnLengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirectionId", DbType="Int")]
		public System.Nullable<int> DirectionId
		{
			get
			{
				return this._DirectionId;
			}
			set
			{
				if ((this._DirectionId != value))
				{
					this.OnDirectionIdChanging(value);
					this.SendPropertyChanging();
					this._DirectionId = value;
					this.SendPropertyChanged("DirectionId");
					this.OnDirectionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHouse", DbType="Bit")]
		public System.Nullable<bool> IsHouse
		{
			get
			{
				return this._IsHouse;
			}
			set
			{
				if ((this._IsHouse != value))
				{
					this.OnIsHouseChanging(value);
					this.SendPropertyChanging();
					this._IsHouse = value;
					this.SendPropertyChanged("IsHouse");
					this.OnIsHouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HouseLevel", DbType="Int")]
		public System.Nullable<int> HouseLevel
		{
			get
			{
				return this._HouseLevel;
			}
			set
			{
				if ((this._HouseLevel != value))
				{
					this.OnHouseLevelChanging(value);
					this.SendPropertyChanging();
					this._HouseLevel = value;
					this.SendPropertyChanged("HouseLevel");
					this.OnHouseLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bedroom", DbType="Int")]
		public System.Nullable<int> Bedroom
		{
			get
			{
				return this._Bedroom;
			}
			set
			{
				if ((this._Bedroom != value))
				{
					this.OnBedroomChanging(value);
					this.SendPropertyChanging();
					this._Bedroom = value;
					this.SendPropertyChanged("Bedroom");
					this.OnBedroomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Restroom", DbType="Int")]
		public System.Nullable<int> Restroom
		{
			get
			{
				return this._Restroom;
			}
			set
			{
				if ((this._Restroom != value))
				{
					this.OnRestroomChanging(value);
					this.SendPropertyChanging();
					this._Restroom = value;
					this.SendPropertyChanged("Restroom");
					this.OnRestroomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Floor", DbType="Int")]
		public System.Nullable<int> Floor
		{
			get
			{
				return this._Floor;
			}
			set
			{
				if ((this._Floor != value))
				{
					this.OnFloorChanging(value);
					this.SendPropertyChanging();
					this._Floor = value;
					this.SendPropertyChanged("Floor");
					this.OnFloorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentPrice", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AgentPrice
		{
			get
			{
				return this._AgentPrice;
			}
			set
			{
				if ((this._AgentPrice != value))
				{
					this.OnAgentPriceChanging(value);
					this.SendPropertyChanging();
					this._AgentPrice = value;
					this.SendPropertyChanged("AgentPrice");
					this.OnAgentPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedPrice", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ExpectedPrice
		{
			get
			{
				return this._ExpectedPrice;
			}
			set
			{
				if ((this._ExpectedPrice != value))
				{
					this.OnExpectedPriceChanging(value);
					this.SendPropertyChanging();
					this._ExpectedPrice = value;
					this.SendPropertyChanged("ExpectedPrice");
					this.OnExpectedPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(MAX)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tax", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Tax
		{
			get
			{
				return this._Tax;
			}
			set
			{
				if ((this._Tax != value))
				{
					this.OnTaxChanging(value);
					this.SendPropertyChanging();
					this._Tax = value;
					this.SendPropertyChanged("Tax");
					this.OnTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMezzanine", DbType="Bit")]
		public System.Nullable<bool> IsMezzanine
		{
			get
			{
				return this._IsMezzanine;
			}
			set
			{
				if ((this._IsMezzanine != value))
				{
					this.OnIsMezzanineChanging(value);
					this.SendPropertyChanging();
					this._IsMezzanine = value;
					this.SendPropertyChanged("IsMezzanine");
					this.OnIsMezzanineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSale", DbType="Bit")]
		public System.Nullable<bool> IsSale
		{
			get
			{
				return this._IsSale;
			}
			set
			{
				if ((this._IsSale != value))
				{
					this.OnIsSaleChanging(value);
					this.SendPropertyChanging();
					this._IsSale = value;
					this.SendPropertyChanged("IsSale");
					this.OnIsSaleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PricePerMet", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PricePerMet
		{
			get
			{
				return this._PricePerMet;
			}
			set
			{
				if ((this._PricePerMet != value))
				{
					this.OnPricePerMetChanging(value);
					this.SendPropertyChanging();
					this._PricePerMet = value;
					this.SendPropertyChanged("PricePerMet");
					this.OnPricePerMetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDetail", DbType="Bit")]
		public System.Nullable<bool> IsDetail
		{
			get
			{
				return this._IsDetail;
			}
			set
			{
				if ((this._IsDetail != value))
				{
					this.OnIsDetailChanging(value);
					this.SendPropertyChanging();
					this._IsDetail = value;
					this.SendPropertyChanged("IsDetail");
					this.OnIsDetailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VLand")]
	public partial class VLand
	{
		
		private int _Id;
		
		private string _Title;
		
		private string _Address;
		
		private System.Nullable<int> _DistrictId;
		
		private System.Nullable<int> _StreetId;
		
		private System.Nullable<decimal> _AlleyWide;
		
		private string _Contact;
		
		private string _Phone;
		
		private System.Nullable<bool> _IsAgent;
		
		private System.Nullable<bool> _IsDue;
		
		private string _Comment;
		
		private System.Nullable<decimal> _Area;
		
		private System.Nullable<decimal> _Wide;
		
		private System.Nullable<decimal> _Length;
		
		private System.Nullable<int> _DirectionId;
		
		private System.Nullable<bool> _IsHouse;
		
		private System.Nullable<int> _HouseLevel;
		
		private System.Nullable<int> _Bedroom;
		
		private System.Nullable<int> _Restroom;
		
		private System.Nullable<int> _Floor;
		
		private System.Nullable<decimal> _Price;
		
		private System.Nullable<decimal> _ExpectedPrice;
		
		private string _Url;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<decimal> _Tax;
		
		private string _Street;
		
		private System.Nullable<decimal> _PricePerMet;
		
		private System.Nullable<decimal> _ExpectedPricePerMet;
		
		private string _Direction;
		
		private string _Ward;
		
		private string _District;
		
		private System.Nullable<bool> _IsMezzanine;
		
		private System.Nullable<decimal> _AgentPrice;
		
		private System.Nullable<bool> _IsSale;
		
		private System.Nullable<int> _WardId;
		
		private System.Nullable<bool> _IsDetail;
		
		public VLand()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(MAX)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistrictId", DbType="Int")]
		public System.Nullable<int> DistrictId
		{
			get
			{
				return this._DistrictId;
			}
			set
			{
				if ((this._DistrictId != value))
				{
					this._DistrictId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetId", DbType="Int")]
		public System.Nullable<int> StreetId
		{
			get
			{
				return this._StreetId;
			}
			set
			{
				if ((this._StreetId != value))
				{
					this._StreetId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlleyWide", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> AlleyWide
		{
			get
			{
				return this._AlleyWide;
			}
			set
			{
				if ((this._AlleyWide != value))
				{
					this._AlleyWide = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="NVarChar(500)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this._Contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAgent", DbType="Bit")]
		public System.Nullable<bool> IsAgent
		{
			get
			{
				return this._IsAgent;
			}
			set
			{
				if ((this._IsAgent != value))
				{
					this._IsAgent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDue", DbType="Bit")]
		public System.Nullable<bool> IsDue
		{
			get
			{
				return this._IsDue;
			}
			set
			{
				if ((this._IsDue != value))
				{
					this._IsDue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Area", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Area
		{
			get
			{
				return this._Area;
			}
			set
			{
				if ((this._Area != value))
				{
					this._Area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wide", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Wide
		{
			get
			{
				return this._Wide;
			}
			set
			{
				if ((this._Wide != value))
				{
					this._Wide = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Length", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Length
		{
			get
			{
				return this._Length;
			}
			set
			{
				if ((this._Length != value))
				{
					this._Length = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirectionId", DbType="Int")]
		public System.Nullable<int> DirectionId
		{
			get
			{
				return this._DirectionId;
			}
			set
			{
				if ((this._DirectionId != value))
				{
					this._DirectionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHouse", DbType="Bit")]
		public System.Nullable<bool> IsHouse
		{
			get
			{
				return this._IsHouse;
			}
			set
			{
				if ((this._IsHouse != value))
				{
					this._IsHouse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HouseLevel", DbType="Int")]
		public System.Nullable<int> HouseLevel
		{
			get
			{
				return this._HouseLevel;
			}
			set
			{
				if ((this._HouseLevel != value))
				{
					this._HouseLevel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bedroom", DbType="Int")]
		public System.Nullable<int> Bedroom
		{
			get
			{
				return this._Bedroom;
			}
			set
			{
				if ((this._Bedroom != value))
				{
					this._Bedroom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Restroom", DbType="Int")]
		public System.Nullable<int> Restroom
		{
			get
			{
				return this._Restroom;
			}
			set
			{
				if ((this._Restroom != value))
				{
					this._Restroom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Floor", DbType="Int")]
		public System.Nullable<int> Floor
		{
			get
			{
				return this._Floor;
			}
			set
			{
				if ((this._Floor != value))
				{
					this._Floor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedPrice", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ExpectedPrice
		{
			get
			{
				return this._ExpectedPrice;
			}
			set
			{
				if ((this._ExpectedPrice != value))
				{
					this._ExpectedPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(MAX)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this._CreatedDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tax", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> Tax
		{
			get
			{
				return this._Tax;
			}
			set
			{
				if ((this._Tax != value))
				{
					this._Tax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(500)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this._Street = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PricePerMet", DbType="Decimal(38,21)")]
		public System.Nullable<decimal> PricePerMet
		{
			get
			{
				return this._PricePerMet;
			}
			set
			{
				if ((this._PricePerMet != value))
				{
					this._PricePerMet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpectedPricePerMet", DbType="Decimal(38,21)")]
		public System.Nullable<decimal> ExpectedPricePerMet
		{
			get
			{
				return this._ExpectedPricePerMet;
			}
			set
			{
				if ((this._ExpectedPricePerMet != value))
				{
					this._ExpectedPricePerMet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direction", DbType="NVarChar(100)")]
		public string Direction
		{
			get
			{
				return this._Direction;
			}
			set
			{
				if ((this._Direction != value))
				{
					this._Direction = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ward", DbType="NVarChar(100)")]
		public string Ward
		{
			get
			{
				return this._Ward;
			}
			set
			{
				if ((this._Ward != value))
				{
					this._Ward = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="NVarChar(100)")]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this._District = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMezzanine", DbType="Bit")]
		public System.Nullable<bool> IsMezzanine
		{
			get
			{
				return this._IsMezzanine;
			}
			set
			{
				if ((this._IsMezzanine != value))
				{
					this._IsMezzanine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentPrice", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> AgentPrice
		{
			get
			{
				return this._AgentPrice;
			}
			set
			{
				if ((this._AgentPrice != value))
				{
					this._AgentPrice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSale", DbType="Bit")]
		public System.Nullable<bool> IsSale
		{
			get
			{
				return this._IsSale;
			}
			set
			{
				if ((this._IsSale != value))
				{
					this._IsSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WardId", DbType="Int")]
		public System.Nullable<int> WardId
		{
			get
			{
				return this._WardId;
			}
			set
			{
				if ((this._WardId != value))
				{
					this._WardId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDetail", DbType="Bit")]
		public System.Nullable<bool> IsDetail
		{
			get
			{
				return this._IsDetail;
			}
			set
			{
				if ((this._IsDetail != value))
				{
					this._IsDetail = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
