#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetHistoricalData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Forex")]
	public partial class HistoricalDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDefinition(Definition instance);
    partial void UpdateDefinition(Definition instance);
    partial void DeleteDefinition(Definition instance);
    partial void InsertEUR(EUR instance);
    partial void UpdateEUR(EUR instance);
    partial void DeleteEUR(EUR instance);
    partial void InsertForex(Forex instance);
    partial void UpdateForex(Forex instance);
    partial void DeleteForex(Forex instance);
    partial void InsertSJCDetail(SJCDetail instance);
    partial void UpdateSJCDetail(SJCDetail instance);
    partial void DeleteSJCDetail(SJCDetail instance);
    partial void InsertSJC(SJC instance);
    partial void UpdateSJC(SJC instance);
    partial void DeleteSJC(SJC instance);
    partial void InsertUSD(USD instance);
    partial void UpdateUSD(USD instance);
    partial void DeleteUSD(USD instance);
    #endregion
		
		public HistoricalDBDataContext() : 
				base(global::GetHistoricalData.Properties.Settings.Default.ForexConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HistoricalDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HistoricalDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HistoricalDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HistoricalDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VAvgMonthGold> VAvgMonthGolds
		{
			get
			{
				return this.GetTable<VAvgMonthGold>();
			}
		}
		
		public System.Data.Linq.Table<VAvgMonthYearGold> VAvgMonthYearGolds
		{
			get
			{
				return this.GetTable<VAvgMonthYearGold>();
			}
		}
		
		public System.Data.Linq.Table<VAvgMonthYearSJC> VAvgMonthYearSJCs
		{
			get
			{
				return this.GetTable<VAvgMonthYearSJC>();
			}
		}
		
		public System.Data.Linq.Table<Definition> Definitions
		{
			get
			{
				return this.GetTable<Definition>();
			}
		}
		
		public System.Data.Linq.Table<EUR> EURs
		{
			get
			{
				return this.GetTable<EUR>();
			}
		}
		
		public System.Data.Linq.Table<Forex> Forexes
		{
			get
			{
				return this.GetTable<Forex>();
			}
		}
		
		public System.Data.Linq.Table<Gold> Golds
		{
			get
			{
				return this.GetTable<Gold>();
			}
		}
		
		public System.Data.Linq.Table<SJCDetail> SJCDetails
		{
			get
			{
				return this.GetTable<SJCDetail>();
			}
		}
		
		public System.Data.Linq.Table<SJC> SJCs
		{
			get
			{
				return this.GetTable<SJC>();
			}
		}
		
		public System.Data.Linq.Table<USD> USDs
		{
			get
			{
				return this.GetTable<USD>();
			}
		}
		
		public System.Data.Linq.Table<VAvgMonthSJC> VAvgMonthSJCs
		{
			get
			{
				return this.GetTable<VAvgMonthSJC>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AvgMonth", IsComposable=true)]
		public IQueryable<AvgMonthResult> AvgMonth([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> checkDate)
		{
			return this.CreateMethodCallQuery<AvgMonthResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), checkDate);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AvgWeekDayGold", IsComposable=true)]
		public IQueryable<AvgWeekDayGoldResult> AvgWeekDayGold([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> checkDate)
		{
			return this.CreateMethodCallQuery<AvgWeekDayGoldResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), checkDate);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AvgMonthGold", IsComposable=true)]
		public IQueryable<AvgMonthGoldResult> AvgMonthGold([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> checkDate)
		{
			return this.CreateMethodCallQuery<AvgMonthGoldResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), checkDate);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AvgMonthYear", IsComposable=true)]
		public IQueryable<AvgMonthYearResult> AvgMonthYear([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> checkDate)
		{
			return this.CreateMethodCallQuery<AvgMonthYearResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), checkDate);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AvgMonthYearGold", IsComposable=true)]
		public IQueryable<AvgMonthYearGoldResult> AvgMonthYearGold([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> checkDate)
		{
			return this.CreateMethodCallQuery<AvgMonthYearGoldResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), checkDate);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.AvgWeekDay", IsComposable=true)]
		public IQueryable<AvgWeekDayResult> AvgWeekDay([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> checkDate)
		{
			return this.CreateMethodCallQuery<AvgWeekDayResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), checkDate);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VAvgMonthGold")]
	public partial class VAvgMonthGold
	{
		
		private System.Nullable<long> _Id;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<decimal> _USD;
		
		private System.Nullable<decimal> _EUR;
		
		private System.Nullable<decimal> _JPY;
		
		private System.Nullable<decimal> _GBP;
		
		private System.Nullable<decimal> _CAD;
		
		private System.Nullable<decimal> _CHF;
		
		private System.Nullable<decimal> _INR;
		
		private System.Nullable<decimal> _CNY;
		
		private System.Nullable<decimal> _TRY;
		
		private System.Nullable<decimal> _SAR;
		
		private System.Nullable<decimal> _IDR;
		
		private System.Nullable<decimal> _AED;
		
		private System.Nullable<decimal> _THB;
		
		private System.Nullable<decimal> _VND;
		
		private System.Nullable<decimal> _EGP;
		
		private System.Nullable<decimal> _KRW;
		
		private System.Nullable<decimal> _RUB;
		
		private System.Nullable<decimal> _ZAR;
		
		private System.Nullable<decimal> _AUD;
		
		private System.Nullable<decimal> _G5;
		
		private System.Nullable<decimal> _PROD;
		
		private System.Nullable<decimal> _CONS;
		
		public VAvgMonthGold()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt")]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> USD
		{
			get
			{
				return this._USD;
			}
			set
			{
				if ((this._USD != value))
				{
					this._USD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EUR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> EUR
		{
			get
			{
				return this._EUR;
			}
			set
			{
				if ((this._EUR != value))
				{
					this._EUR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JPY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> JPY
		{
			get
			{
				return this._JPY;
			}
			set
			{
				if ((this._JPY != value))
				{
					this._JPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GBP", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> GBP
		{
			get
			{
				return this._GBP;
			}
			set
			{
				if ((this._GBP != value))
				{
					this._GBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CAD
		{
			get
			{
				return this._CAD;
			}
			set
			{
				if ((this._CAD != value))
				{
					this._CAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHF", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CHF
		{
			get
			{
				return this._CHF;
			}
			set
			{
				if ((this._CHF != value))
				{
					this._CHF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> INR
		{
			get
			{
				return this._INR;
			}
			set
			{
				if ((this._INR != value))
				{
					this._INR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CNY
		{
			get
			{
				return this._CNY;
			}
			set
			{
				if ((this._CNY != value))
				{
					this._CNY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> TRY
		{
			get
			{
				return this._TRY;
			}
			set
			{
				if ((this._TRY != value))
				{
					this._TRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> SAR
		{
			get
			{
				return this._SAR;
			}
			set
			{
				if ((this._SAR != value))
				{
					this._SAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> IDR
		{
			get
			{
				return this._IDR;
			}
			set
			{
				if ((this._IDR != value))
				{
					this._IDR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AED", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AED
		{
			get
			{
				return this._AED;
			}
			set
			{
				if ((this._AED != value))
				{
					this._AED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THB", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> THB
		{
			get
			{
				return this._THB;
			}
			set
			{
				if ((this._THB != value))
				{
					this._THB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VND", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> VND
		{
			get
			{
				return this._VND;
			}
			set
			{
				if ((this._VND != value))
				{
					this._VND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EGP", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> EGP
		{
			get
			{
				return this._EGP;
			}
			set
			{
				if ((this._EGP != value))
				{
					this._EGP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KRW", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> KRW
		{
			get
			{
				return this._KRW;
			}
			set
			{
				if ((this._KRW != value))
				{
					this._KRW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUB", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> RUB
		{
			get
			{
				return this._RUB;
			}
			set
			{
				if ((this._RUB != value))
				{
					this._RUB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> ZAR
		{
			get
			{
				return this._ZAR;
			}
			set
			{
				if ((this._ZAR != value))
				{
					this._ZAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AUD
		{
			get
			{
				return this._AUD;
			}
			set
			{
				if ((this._AUD != value))
				{
					this._AUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G5", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> G5
		{
			get
			{
				return this._G5;
			}
			set
			{
				if ((this._G5 != value))
				{
					this._G5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> PROD
		{
			get
			{
				return this._PROD;
			}
			set
			{
				if ((this._PROD != value))
				{
					this._PROD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONS", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CONS
		{
			get
			{
				return this._CONS;
			}
			set
			{
				if ((this._CONS != value))
				{
					this._CONS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VAvgMonthYearGold")]
	public partial class VAvgMonthYearGold
	{
		
		private System.Nullable<long> _Id;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<decimal> _USD;
		
		private System.Nullable<decimal> _EUR;
		
		private System.Nullable<decimal> _JPY;
		
		private System.Nullable<decimal> _GBP;
		
		private System.Nullable<decimal> _CAD;
		
		private System.Nullable<decimal> _CHF;
		
		private System.Nullable<decimal> _INR;
		
		private System.Nullable<decimal> _CNY;
		
		private System.Nullable<decimal> _TRY;
		
		private System.Nullable<decimal> _SAR;
		
		private System.Nullable<decimal> _IDR;
		
		private System.Nullable<decimal> _AED;
		
		private System.Nullable<decimal> _THB;
		
		private System.Nullable<decimal> _VND;
		
		private System.Nullable<decimal> _EGP;
		
		private System.Nullable<decimal> _KRW;
		
		private System.Nullable<decimal> _RUB;
		
		private System.Nullable<decimal> _ZAR;
		
		private System.Nullable<decimal> _AUD;
		
		private System.Nullable<decimal> _G5;
		
		private System.Nullable<decimal> _PROD;
		
		private System.Nullable<decimal> _CONS;
		
		public VAvgMonthYearGold()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt")]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> USD
		{
			get
			{
				return this._USD;
			}
			set
			{
				if ((this._USD != value))
				{
					this._USD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EUR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> EUR
		{
			get
			{
				return this._EUR;
			}
			set
			{
				if ((this._EUR != value))
				{
					this._EUR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JPY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> JPY
		{
			get
			{
				return this._JPY;
			}
			set
			{
				if ((this._JPY != value))
				{
					this._JPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GBP", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> GBP
		{
			get
			{
				return this._GBP;
			}
			set
			{
				if ((this._GBP != value))
				{
					this._GBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CAD
		{
			get
			{
				return this._CAD;
			}
			set
			{
				if ((this._CAD != value))
				{
					this._CAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHF", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CHF
		{
			get
			{
				return this._CHF;
			}
			set
			{
				if ((this._CHF != value))
				{
					this._CHF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> INR
		{
			get
			{
				return this._INR;
			}
			set
			{
				if ((this._INR != value))
				{
					this._INR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CNY
		{
			get
			{
				return this._CNY;
			}
			set
			{
				if ((this._CNY != value))
				{
					this._CNY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> TRY
		{
			get
			{
				return this._TRY;
			}
			set
			{
				if ((this._TRY != value))
				{
					this._TRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> SAR
		{
			get
			{
				return this._SAR;
			}
			set
			{
				if ((this._SAR != value))
				{
					this._SAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> IDR
		{
			get
			{
				return this._IDR;
			}
			set
			{
				if ((this._IDR != value))
				{
					this._IDR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AED", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AED
		{
			get
			{
				return this._AED;
			}
			set
			{
				if ((this._AED != value))
				{
					this._AED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THB", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> THB
		{
			get
			{
				return this._THB;
			}
			set
			{
				if ((this._THB != value))
				{
					this._THB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VND", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> VND
		{
			get
			{
				return this._VND;
			}
			set
			{
				if ((this._VND != value))
				{
					this._VND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EGP", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> EGP
		{
			get
			{
				return this._EGP;
			}
			set
			{
				if ((this._EGP != value))
				{
					this._EGP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KRW", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> KRW
		{
			get
			{
				return this._KRW;
			}
			set
			{
				if ((this._KRW != value))
				{
					this._KRW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUB", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> RUB
		{
			get
			{
				return this._RUB;
			}
			set
			{
				if ((this._RUB != value))
				{
					this._RUB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> ZAR
		{
			get
			{
				return this._ZAR;
			}
			set
			{
				if ((this._ZAR != value))
				{
					this._ZAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AUD
		{
			get
			{
				return this._AUD;
			}
			set
			{
				if ((this._AUD != value))
				{
					this._AUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G5", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> G5
		{
			get
			{
				return this._G5;
			}
			set
			{
				if ((this._G5 != value))
				{
					this._G5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> PROD
		{
			get
			{
				return this._PROD;
			}
			set
			{
				if ((this._PROD != value))
				{
					this._PROD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONS", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CONS
		{
			get
			{
				return this._CONS;
			}
			set
			{
				if ((this._CONS != value))
				{
					this._CONS = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VAvgMonthYearSJC")]
	public partial class VAvgMonthYearSJC
	{
		
		private System.Nullable<long> _Id;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<decimal> _AvgBuy;
		
		private System.Nullable<decimal> _AvgSell;
		
		public VAvgMonthYearSJC()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt")]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgBuy", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AvgBuy
		{
			get
			{
				return this._AvgBuy;
			}
			set
			{
				if ((this._AvgBuy != value))
				{
					this._AvgBuy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgSell", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AvgSell
		{
			get
			{
				return this._AvgSell;
			}
			set
			{
				if ((this._AvgSell != value))
				{
					this._AvgSell = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Definition")]
	public partial class Definition : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _CodeNum;
		
		private string _Definition1;
		
		private System.Nullable<int> _GroupId;
		
		private string _Description;
		
		private System.Nullable<bool> _Bit;
		
		private System.Nullable<int> _UserId;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _Num1;
		
		private System.Nullable<int> _Num2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCodeNumChanging(string value);
    partial void OnCodeNumChanged();
    partial void OnDefinition1Changing(string value);
    partial void OnDefinition1Changed();
    partial void OnGroupIdChanging(System.Nullable<int> value);
    partial void OnGroupIdChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnBitChanging(System.Nullable<bool> value);
    partial void OnBitChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnNum1Changing(System.Nullable<int> value);
    partial void OnNum1Changed();
    partial void OnNum2Changing(System.Nullable<int> value);
    partial void OnNum2Changed();
    #endregion
		
		public Definition()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeNum", DbType="NVarChar(100)")]
		public string CodeNum
		{
			get
			{
				return this._CodeNum;
			}
			set
			{
				if ((this._CodeNum != value))
				{
					this.OnCodeNumChanging(value);
					this.SendPropertyChanging();
					this._CodeNum = value;
					this.SendPropertyChanged("CodeNum");
					this.OnCodeNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Definition", Storage="_Definition1", DbType="NVarChar(100)")]
		public string Definition1
		{
			get
			{
				return this._Definition1;
			}
			set
			{
				if ((this._Definition1 != value))
				{
					this.OnDefinition1Changing(value);
					this.SendPropertyChanging();
					this._Definition1 = value;
					this.SendPropertyChanged("Definition1");
					this.OnDefinition1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int")]
		public System.Nullable<int> GroupId
		{
			get
			{
				return this._GroupId;
			}
			set
			{
				if ((this._GroupId != value))
				{
					this.OnGroupIdChanging(value);
					this.SendPropertyChanging();
					this._GroupId = value;
					this.SendPropertyChanged("GroupId");
					this.OnGroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(1000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bit", DbType="Bit")]
		public System.Nullable<bool> Bit
		{
			get
			{
				return this._Bit;
			}
			set
			{
				if ((this._Bit != value))
				{
					this.OnBitChanging(value);
					this.SendPropertyChanging();
					this._Bit = value;
					this.SendPropertyChanged("Bit");
					this.OnBitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num1", DbType="Int")]
		public System.Nullable<int> Num1
		{
			get
			{
				return this._Num1;
			}
			set
			{
				if ((this._Num1 != value))
				{
					this.OnNum1Changing(value);
					this.SendPropertyChanging();
					this._Num1 = value;
					this.SendPropertyChanged("Num1");
					this.OnNum1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num2", DbType="Int")]
		public System.Nullable<int> Num2
		{
			get
			{
				return this._Num2;
			}
			set
			{
				if ((this._Num2 != value))
				{
					this.OnNum2Changing(value);
					this.SendPropertyChanging();
					this._Num2 = value;
					this.SendPropertyChanged("Num2");
					this.OnNum2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EUR")]
	public partial class EUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _PriceDate;
		
		private System.Nullable<decimal> _Buy;
		
		private System.Nullable<decimal> _Transfer;
		
		private System.Nullable<decimal> _Sell;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPriceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPriceDateChanged();
    partial void OnBuyChanging(System.Nullable<decimal> value);
    partial void OnBuyChanged();
    partial void OnTransferChanging(System.Nullable<decimal> value);
    partial void OnTransferChanged();
    partial void OnSellChanging(System.Nullable<decimal> value);
    partial void OnSellChanged();
    #endregion
		
		public EUR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PriceDate
		{
			get
			{
				return this._PriceDate;
			}
			set
			{
				if ((this._PriceDate != value))
				{
					this.OnPriceDateChanging(value);
					this.SendPropertyChanging();
					this._PriceDate = value;
					this.SendPropertyChanged("PriceDate");
					this.OnPriceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Buy
		{
			get
			{
				return this._Buy;
			}
			set
			{
				if ((this._Buy != value))
				{
					this.OnBuyChanging(value);
					this.SendPropertyChanging();
					this._Buy = value;
					this.SendPropertyChanged("Buy");
					this.OnBuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transfer", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Transfer
		{
			get
			{
				return this._Transfer;
			}
			set
			{
				if ((this._Transfer != value))
				{
					this.OnTransferChanging(value);
					this.SendPropertyChanging();
					this._Transfer = value;
					this.SendPropertyChanged("Transfer");
					this.OnTransferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sell", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Sell
		{
			get
			{
				return this._Sell;
			}
			set
			{
				if ((this._Sell != value))
				{
					this.OnSellChanging(value);
					this.SendPropertyChanging();
					this._Sell = value;
					this.SendPropertyChanged("Sell");
					this.OnSellChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Forex")]
	public partial class Forex : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _ItemId;
		
		private System.Nullable<System.DateTime> _PriceDate;
		
		private System.Nullable<decimal> _Buy;
		
		private System.Nullable<decimal> _Transfer;
		
		private System.Nullable<decimal> _Sell;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnItemIdChanging(System.Nullable<int> value);
    partial void OnItemIdChanged();
    partial void OnPriceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPriceDateChanged();
    partial void OnBuyChanging(System.Nullable<decimal> value);
    partial void OnBuyChanged();
    partial void OnTransferChanging(System.Nullable<decimal> value);
    partial void OnTransferChanged();
    partial void OnSellChanging(System.Nullable<decimal> value);
    partial void OnSellChanged();
    #endregion
		
		public Forex()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemId", DbType="Int")]
		public System.Nullable<int> ItemId
		{
			get
			{
				return this._ItemId;
			}
			set
			{
				if ((this._ItemId != value))
				{
					this.OnItemIdChanging(value);
					this.SendPropertyChanging();
					this._ItemId = value;
					this.SendPropertyChanged("ItemId");
					this.OnItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PriceDate
		{
			get
			{
				return this._PriceDate;
			}
			set
			{
				if ((this._PriceDate != value))
				{
					this.OnPriceDateChanging(value);
					this.SendPropertyChanging();
					this._PriceDate = value;
					this.SendPropertyChanged("PriceDate");
					this.OnPriceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Buy
		{
			get
			{
				return this._Buy;
			}
			set
			{
				if ((this._Buy != value))
				{
					this.OnBuyChanging(value);
					this.SendPropertyChanging();
					this._Buy = value;
					this.SendPropertyChanged("Buy");
					this.OnBuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transfer", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Transfer
		{
			get
			{
				return this._Transfer;
			}
			set
			{
				if ((this._Transfer != value))
				{
					this.OnTransferChanging(value);
					this.SendPropertyChanging();
					this._Transfer = value;
					this.SendPropertyChanged("Transfer");
					this.OnTransferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sell", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Sell
		{
			get
			{
				return this._Sell;
			}
			set
			{
				if ((this._Sell != value))
				{
					this.OnSellChanging(value);
					this.SendPropertyChanging();
					this._Sell = value;
					this.SendPropertyChanged("Sell");
					this.OnSellChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gold")]
	public partial class Gold
	{
		
		private System.Nullable<System.DateTime> _PriceDate;
		
		private System.Nullable<decimal> _USD;
		
		private System.Nullable<decimal> _EUR;
		
		private System.Nullable<decimal> _JPY;
		
		private System.Nullable<decimal> _GBP;
		
		private System.Nullable<decimal> _CAD;
		
		private System.Nullable<decimal> _CHF;
		
		private System.Nullable<decimal> _INR;
		
		private System.Nullable<decimal> _CNY;
		
		private System.Nullable<decimal> _TRY;
		
		private System.Nullable<decimal> _SAR;
		
		private System.Nullable<decimal> _IDR;
		
		private System.Nullable<decimal> _AED;
		
		private System.Nullable<decimal> _THB;
		
		private System.Nullable<decimal> _VND;
		
		private System.Nullable<decimal> _EGP;
		
		private System.Nullable<decimal> _KRW;
		
		private System.Nullable<decimal> _RUB;
		
		private System.Nullable<decimal> _ZAR;
		
		private System.Nullable<decimal> _AUD;
		
		private System.Nullable<decimal> _G5_CCY;
		
		private System.Nullable<decimal> _PROD_IDX;
		
		private System.Nullable<decimal> _CONS_IDX;
		
		public Gold()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PriceDate
		{
			get
			{
				return this._PriceDate;
			}
			set
			{
				if ((this._PriceDate != value))
				{
					this._PriceDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USD", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> USD
		{
			get
			{
				return this._USD;
			}
			set
			{
				if ((this._USD != value))
				{
					this._USD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EUR", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> EUR
		{
			get
			{
				return this._EUR;
			}
			set
			{
				if ((this._EUR != value))
				{
					this._EUR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JPY", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> JPY
		{
			get
			{
				return this._JPY;
			}
			set
			{
				if ((this._JPY != value))
				{
					this._JPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GBP", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> GBP
		{
			get
			{
				return this._GBP;
			}
			set
			{
				if ((this._GBP != value))
				{
					this._GBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAD", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> CAD
		{
			get
			{
				return this._CAD;
			}
			set
			{
				if ((this._CAD != value))
				{
					this._CAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHF", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> CHF
		{
			get
			{
				return this._CHF;
			}
			set
			{
				if ((this._CHF != value))
				{
					this._CHF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INR", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> INR
		{
			get
			{
				return this._INR;
			}
			set
			{
				if ((this._INR != value))
				{
					this._INR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNY", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> CNY
		{
			get
			{
				return this._CNY;
			}
			set
			{
				if ((this._CNY != value))
				{
					this._CNY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRY", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> TRY
		{
			get
			{
				return this._TRY;
			}
			set
			{
				if ((this._TRY != value))
				{
					this._TRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAR", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> SAR
		{
			get
			{
				return this._SAR;
			}
			set
			{
				if ((this._SAR != value))
				{
					this._SAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDR", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> IDR
		{
			get
			{
				return this._IDR;
			}
			set
			{
				if ((this._IDR != value))
				{
					this._IDR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AED", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> AED
		{
			get
			{
				return this._AED;
			}
			set
			{
				if ((this._AED != value))
				{
					this._AED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THB", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> THB
		{
			get
			{
				return this._THB;
			}
			set
			{
				if ((this._THB != value))
				{
					this._THB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VND", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> VND
		{
			get
			{
				return this._VND;
			}
			set
			{
				if ((this._VND != value))
				{
					this._VND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EGP", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> EGP
		{
			get
			{
				return this._EGP;
			}
			set
			{
				if ((this._EGP != value))
				{
					this._EGP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KRW", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> KRW
		{
			get
			{
				return this._KRW;
			}
			set
			{
				if ((this._KRW != value))
				{
					this._KRW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUB", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> RUB
		{
			get
			{
				return this._RUB;
			}
			set
			{
				if ((this._RUB != value))
				{
					this._RUB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAR", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> ZAR
		{
			get
			{
				return this._ZAR;
			}
			set
			{
				if ((this._ZAR != value))
				{
					this._ZAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUD", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> AUD
		{
			get
			{
				return this._AUD;
			}
			set
			{
				if ((this._AUD != value))
				{
					this._AUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G5_CCY", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> G5_CCY
		{
			get
			{
				return this._G5_CCY;
			}
			set
			{
				if ((this._G5_CCY != value))
				{
					this._G5_CCY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD_IDX", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> PROD_IDX
		{
			get
			{
				return this._PROD_IDX;
			}
			set
			{
				if ((this._PROD_IDX != value))
				{
					this._PROD_IDX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONS_IDX", DbType="Decimal(18,1)")]
		public System.Nullable<decimal> CONS_IDX
		{
			get
			{
				return this._CONS_IDX;
			}
			set
			{
				if ((this._CONS_IDX != value))
				{
					this._CONS_IDX = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SJCDetail")]
	public partial class SJCDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _PriceDate;
		
		private System.Nullable<int> _CityId;
		
		private System.Nullable<int> _ItemId;
		
		private System.Nullable<decimal> _Buy;
		
		private System.Nullable<decimal> _Sell;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPriceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPriceDateChanged();
    partial void OnCityIdChanging(System.Nullable<int> value);
    partial void OnCityIdChanged();
    partial void OnItemIdChanging(System.Nullable<int> value);
    partial void OnItemIdChanged();
    partial void OnBuyChanging(System.Nullable<decimal> value);
    partial void OnBuyChanged();
    partial void OnSellChanging(System.Nullable<decimal> value);
    partial void OnSellChanged();
    #endregion
		
		public SJCDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PriceDate
		{
			get
			{
				return this._PriceDate;
			}
			set
			{
				if ((this._PriceDate != value))
				{
					this.OnPriceDateChanging(value);
					this.SendPropertyChanging();
					this._PriceDate = value;
					this.SendPropertyChanged("PriceDate");
					this.OnPriceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityId", DbType="Int")]
		public System.Nullable<int> CityId
		{
			get
			{
				return this._CityId;
			}
			set
			{
				if ((this._CityId != value))
				{
					this.OnCityIdChanging(value);
					this.SendPropertyChanging();
					this._CityId = value;
					this.SendPropertyChanged("CityId");
					this.OnCityIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemId", DbType="Int")]
		public System.Nullable<int> ItemId
		{
			get
			{
				return this._ItemId;
			}
			set
			{
				if ((this._ItemId != value))
				{
					this.OnItemIdChanging(value);
					this.SendPropertyChanging();
					this._ItemId = value;
					this.SendPropertyChanged("ItemId");
					this.OnItemIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Buy
		{
			get
			{
				return this._Buy;
			}
			set
			{
				if ((this._Buy != value))
				{
					this.OnBuyChanging(value);
					this.SendPropertyChanging();
					this._Buy = value;
					this.SendPropertyChanged("Buy");
					this.OnBuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sell", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Sell
		{
			get
			{
				return this._Sell;
			}
			set
			{
				if ((this._Sell != value))
				{
					this.OnSellChanging(value);
					this.SendPropertyChanging();
					this._Sell = value;
					this.SendPropertyChanged("Sell");
					this.OnSellChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SJC")]
	public partial class SJC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _PriceDate;
		
		private System.Nullable<decimal> _Buy;
		
		private System.Nullable<decimal> _Sell;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPriceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPriceDateChanged();
    partial void OnBuyChanging(System.Nullable<decimal> value);
    partial void OnBuyChanged();
    partial void OnSellChanging(System.Nullable<decimal> value);
    partial void OnSellChanged();
    #endregion
		
		public SJC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PriceDate
		{
			get
			{
				return this._PriceDate;
			}
			set
			{
				if ((this._PriceDate != value))
				{
					this.OnPriceDateChanging(value);
					this.SendPropertyChanging();
					this._PriceDate = value;
					this.SendPropertyChanged("PriceDate");
					this.OnPriceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Buy
		{
			get
			{
				return this._Buy;
			}
			set
			{
				if ((this._Buy != value))
				{
					this.OnBuyChanging(value);
					this.SendPropertyChanging();
					this._Buy = value;
					this.SendPropertyChanged("Buy");
					this.OnBuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sell", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Sell
		{
			get
			{
				return this._Sell;
			}
			set
			{
				if ((this._Sell != value))
				{
					this.OnSellChanging(value);
					this.SendPropertyChanging();
					this._Sell = value;
					this.SendPropertyChanged("Sell");
					this.OnSellChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USD")]
	public partial class USD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _PriceDate;
		
		private System.Nullable<decimal> _Buy;
		
		private System.Nullable<decimal> _Transfer;
		
		private System.Nullable<decimal> _Sell;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPriceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnPriceDateChanged();
    partial void OnBuyChanging(System.Nullable<decimal> value);
    partial void OnBuyChanged();
    partial void OnTransferChanging(System.Nullable<decimal> value);
    partial void OnTransferChanged();
    partial void OnSellChanging(System.Nullable<decimal> value);
    partial void OnSellChanged();
    #endregion
		
		public USD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> PriceDate
		{
			get
			{
				return this._PriceDate;
			}
			set
			{
				if ((this._PriceDate != value))
				{
					this.OnPriceDateChanging(value);
					this.SendPropertyChanging();
					this._PriceDate = value;
					this.SendPropertyChanged("PriceDate");
					this.OnPriceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Buy
		{
			get
			{
				return this._Buy;
			}
			set
			{
				if ((this._Buy != value))
				{
					this.OnBuyChanging(value);
					this.SendPropertyChanging();
					this._Buy = value;
					this.SendPropertyChanged("Buy");
					this.OnBuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transfer", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Transfer
		{
			get
			{
				return this._Transfer;
			}
			set
			{
				if ((this._Transfer != value))
				{
					this.OnTransferChanging(value);
					this.SendPropertyChanging();
					this._Transfer = value;
					this.SendPropertyChanged("Transfer");
					this.OnTransferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sell", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Sell
		{
			get
			{
				return this._Sell;
			}
			set
			{
				if ((this._Sell != value))
				{
					this.OnSellChanging(value);
					this.SendPropertyChanging();
					this._Sell = value;
					this.SendPropertyChanged("Sell");
					this.OnSellChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VAvgMonthSJC")]
	public partial class VAvgMonthSJC
	{
		
		private System.Nullable<long> _Id;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<decimal> _AvgBuy;
		
		private System.Nullable<decimal> _AvgSell;
		
		public VAvgMonthSJC()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt")]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgBuy", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AvgBuy
		{
			get
			{
				return this._AvgBuy;
			}
			set
			{
				if ((this._AvgBuy != value))
				{
					this._AvgBuy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgSell", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AvgSell
		{
			get
			{
				return this._AvgSell;
			}
			set
			{
				if ((this._AvgSell != value))
				{
					this._AvgSell = value;
				}
			}
		}
	}
	
	public partial class AvgMonthResult
	{
		
		private System.Nullable<long> _Id;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<decimal> _AvgBuy;
		
		private System.Nullable<decimal> _AvgSell;
		
		public AvgMonthResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt")]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgBuy", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AvgBuy
		{
			get
			{
				return this._AvgBuy;
			}
			set
			{
				if ((this._AvgBuy != value))
				{
					this._AvgBuy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgSell", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AvgSell
		{
			get
			{
				return this._AvgSell;
			}
			set
			{
				if ((this._AvgSell != value))
				{
					this._AvgSell = value;
				}
			}
		}
	}
	
	public partial class AvgWeekDayGoldResult
	{
		
		private System.Nullable<long> _Id;
		
		private System.Nullable<int> _WeekDayNum;
		
		private string _WeekDay;
		
		private System.Nullable<decimal> _USD;
		
		private System.Nullable<decimal> _EUR;
		
		private System.Nullable<decimal> _JPY;
		
		private System.Nullable<decimal> _GBP;
		
		private System.Nullable<decimal> _CAD;
		
		private System.Nullable<decimal> _CHF;
		
		private System.Nullable<decimal> _INR;
		
		private System.Nullable<decimal> _CNY;
		
		private System.Nullable<decimal> _TRY;
		
		private System.Nullable<decimal> _SAR;
		
		private System.Nullable<decimal> _IDR;
		
		private System.Nullable<decimal> _AED;
		
		private System.Nullable<decimal> _THB;
		
		private System.Nullable<decimal> _VND;
		
		private System.Nullable<decimal> _EGP;
		
		private System.Nullable<decimal> _KRW;
		
		private System.Nullable<decimal> _RUB;
		
		private System.Nullable<decimal> _ZAR;
		
		private System.Nullable<decimal> _AUD;
		
		private System.Nullable<decimal> _G5;
		
		private System.Nullable<decimal> _PROD;
		
		private System.Nullable<decimal> _CONS;
		
		public AvgWeekDayGoldResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt")]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekDayNum", DbType="Int")]
		public System.Nullable<int> WeekDayNum
		{
			get
			{
				return this._WeekDayNum;
			}
			set
			{
				if ((this._WeekDayNum != value))
				{
					this._WeekDayNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekDay", DbType="NVarChar(30)")]
		public string WeekDay
		{
			get
			{
				return this._WeekDay;
			}
			set
			{
				if ((this._WeekDay != value))
				{
					this._WeekDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> USD
		{
			get
			{
				return this._USD;
			}
			set
			{
				if ((this._USD != value))
				{
					this._USD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EUR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> EUR
		{
			get
			{
				return this._EUR;
			}
			set
			{
				if ((this._EUR != value))
				{
					this._EUR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JPY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> JPY
		{
			get
			{
				return this._JPY;
			}
			set
			{
				if ((this._JPY != value))
				{
					this._JPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GBP", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> GBP
		{
			get
			{
				return this._GBP;
			}
			set
			{
				if ((this._GBP != value))
				{
					this._GBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CAD
		{
			get
			{
				return this._CAD;
			}
			set
			{
				if ((this._CAD != value))
				{
					this._CAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHF", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CHF
		{
			get
			{
				return this._CHF;
			}
			set
			{
				if ((this._CHF != value))
				{
					this._CHF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> INR
		{
			get
			{
				return this._INR;
			}
			set
			{
				if ((this._INR != value))
				{
					this._INR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CNY
		{
			get
			{
				return this._CNY;
			}
			set
			{
				if ((this._CNY != value))
				{
					this._CNY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> TRY
		{
			get
			{
				return this._TRY;
			}
			set
			{
				if ((this._TRY != value))
				{
					this._TRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> SAR
		{
			get
			{
				return this._SAR;
			}
			set
			{
				if ((this._SAR != value))
				{
					this._SAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> IDR
		{
			get
			{
				return this._IDR;
			}
			set
			{
				if ((this._IDR != value))
				{
					this._IDR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AED", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AED
		{
			get
			{
				return this._AED;
			}
			set
			{
				if ((this._AED != value))
				{
					this._AED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THB", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> THB
		{
			get
			{
				return this._THB;
			}
			set
			{
				if ((this._THB != value))
				{
					this._THB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VND", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> VND
		{
			get
			{
				return this._VND;
			}
			set
			{
				if ((this._VND != value))
				{
					this._VND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EGP", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> EGP
		{
			get
			{
				return this._EGP;
			}
			set
			{
				if ((this._EGP != value))
				{
					this._EGP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KRW", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> KRW
		{
			get
			{
				return this._KRW;
			}
			set
			{
				if ((this._KRW != value))
				{
					this._KRW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUB", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> RUB
		{
			get
			{
				return this._RUB;
			}
			set
			{
				if ((this._RUB != value))
				{
					this._RUB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> ZAR
		{
			get
			{
				return this._ZAR;
			}
			set
			{
				if ((this._ZAR != value))
				{
					this._ZAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AUD
		{
			get
			{
				return this._AUD;
			}
			set
			{
				if ((this._AUD != value))
				{
					this._AUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G5", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> G5
		{
			get
			{
				return this._G5;
			}
			set
			{
				if ((this._G5 != value))
				{
					this._G5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> PROD
		{
			get
			{
				return this._PROD;
			}
			set
			{
				if ((this._PROD != value))
				{
					this._PROD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONS", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CONS
		{
			get
			{
				return this._CONS;
			}
			set
			{
				if ((this._CONS != value))
				{
					this._CONS = value;
				}
			}
		}
	}
	
	public partial class AvgMonthGoldResult
	{
		
		private System.Nullable<long> _Id;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<decimal> _USD;
		
		private System.Nullable<decimal> _EUR;
		
		private System.Nullable<decimal> _JPY;
		
		private System.Nullable<decimal> _GBP;
		
		private System.Nullable<decimal> _CAD;
		
		private System.Nullable<decimal> _CHF;
		
		private System.Nullable<decimal> _INR;
		
		private System.Nullable<decimal> _CNY;
		
		private System.Nullable<decimal> _TRY;
		
		private System.Nullable<decimal> _SAR;
		
		private System.Nullable<decimal> _IDR;
		
		private System.Nullable<decimal> _AED;
		
		private System.Nullable<decimal> _THB;
		
		private System.Nullable<decimal> _VND;
		
		private System.Nullable<decimal> _EGP;
		
		private System.Nullable<decimal> _KRW;
		
		private System.Nullable<decimal> _RUB;
		
		private System.Nullable<decimal> _ZAR;
		
		private System.Nullable<decimal> _AUD;
		
		private System.Nullable<decimal> _G5;
		
		private System.Nullable<decimal> _PROD;
		
		private System.Nullable<decimal> _CONS;
		
		public AvgMonthGoldResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt")]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> USD
		{
			get
			{
				return this._USD;
			}
			set
			{
				if ((this._USD != value))
				{
					this._USD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EUR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> EUR
		{
			get
			{
				return this._EUR;
			}
			set
			{
				if ((this._EUR != value))
				{
					this._EUR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JPY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> JPY
		{
			get
			{
				return this._JPY;
			}
			set
			{
				if ((this._JPY != value))
				{
					this._JPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GBP", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> GBP
		{
			get
			{
				return this._GBP;
			}
			set
			{
				if ((this._GBP != value))
				{
					this._GBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CAD
		{
			get
			{
				return this._CAD;
			}
			set
			{
				if ((this._CAD != value))
				{
					this._CAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHF", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CHF
		{
			get
			{
				return this._CHF;
			}
			set
			{
				if ((this._CHF != value))
				{
					this._CHF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> INR
		{
			get
			{
				return this._INR;
			}
			set
			{
				if ((this._INR != value))
				{
					this._INR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CNY
		{
			get
			{
				return this._CNY;
			}
			set
			{
				if ((this._CNY != value))
				{
					this._CNY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> TRY
		{
			get
			{
				return this._TRY;
			}
			set
			{
				if ((this._TRY != value))
				{
					this._TRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> SAR
		{
			get
			{
				return this._SAR;
			}
			set
			{
				if ((this._SAR != value))
				{
					this._SAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> IDR
		{
			get
			{
				return this._IDR;
			}
			set
			{
				if ((this._IDR != value))
				{
					this._IDR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AED", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AED
		{
			get
			{
				return this._AED;
			}
			set
			{
				if ((this._AED != value))
				{
					this._AED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THB", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> THB
		{
			get
			{
				return this._THB;
			}
			set
			{
				if ((this._THB != value))
				{
					this._THB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VND", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> VND
		{
			get
			{
				return this._VND;
			}
			set
			{
				if ((this._VND != value))
				{
					this._VND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EGP", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> EGP
		{
			get
			{
				return this._EGP;
			}
			set
			{
				if ((this._EGP != value))
				{
					this._EGP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KRW", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> KRW
		{
			get
			{
				return this._KRW;
			}
			set
			{
				if ((this._KRW != value))
				{
					this._KRW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUB", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> RUB
		{
			get
			{
				return this._RUB;
			}
			set
			{
				if ((this._RUB != value))
				{
					this._RUB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> ZAR
		{
			get
			{
				return this._ZAR;
			}
			set
			{
				if ((this._ZAR != value))
				{
					this._ZAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AUD
		{
			get
			{
				return this._AUD;
			}
			set
			{
				if ((this._AUD != value))
				{
					this._AUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G5", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> G5
		{
			get
			{
				return this._G5;
			}
			set
			{
				if ((this._G5 != value))
				{
					this._G5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> PROD
		{
			get
			{
				return this._PROD;
			}
			set
			{
				if ((this._PROD != value))
				{
					this._PROD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONS", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CONS
		{
			get
			{
				return this._CONS;
			}
			set
			{
				if ((this._CONS != value))
				{
					this._CONS = value;
				}
			}
		}
	}
	
	public partial class AvgMonthYearResult
	{
		
		private System.Nullable<long> _Id;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<decimal> _AvgBuy;
		
		private System.Nullable<decimal> _AvgSell;
		
		public AvgMonthYearResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt")]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgBuy", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AvgBuy
		{
			get
			{
				return this._AvgBuy;
			}
			set
			{
				if ((this._AvgBuy != value))
				{
					this._AvgBuy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgSell", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AvgSell
		{
			get
			{
				return this._AvgSell;
			}
			set
			{
				if ((this._AvgSell != value))
				{
					this._AvgSell = value;
				}
			}
		}
	}
	
	public partial class AvgMonthYearGoldResult
	{
		
		private System.Nullable<long> _Id;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<decimal> _USD;
		
		private System.Nullable<decimal> _EUR;
		
		private System.Nullable<decimal> _JPY;
		
		private System.Nullable<decimal> _GBP;
		
		private System.Nullable<decimal> _CAD;
		
		private System.Nullable<decimal> _CHF;
		
		private System.Nullable<decimal> _INR;
		
		private System.Nullable<decimal> _CNY;
		
		private System.Nullable<decimal> _TRY;
		
		private System.Nullable<decimal> _SAR;
		
		private System.Nullable<decimal> _IDR;
		
		private System.Nullable<decimal> _AED;
		
		private System.Nullable<decimal> _THB;
		
		private System.Nullable<decimal> _VND;
		
		private System.Nullable<decimal> _EGP;
		
		private System.Nullable<decimal> _KRW;
		
		private System.Nullable<decimal> _RUB;
		
		private System.Nullable<decimal> _ZAR;
		
		private System.Nullable<decimal> _AUD;
		
		private System.Nullable<decimal> _G5;
		
		private System.Nullable<decimal> _PROD;
		
		private System.Nullable<decimal> _CONS;
		
		public AvgMonthYearGoldResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt")]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> USD
		{
			get
			{
				return this._USD;
			}
			set
			{
				if ((this._USD != value))
				{
					this._USD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EUR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> EUR
		{
			get
			{
				return this._EUR;
			}
			set
			{
				if ((this._EUR != value))
				{
					this._EUR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JPY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> JPY
		{
			get
			{
				return this._JPY;
			}
			set
			{
				if ((this._JPY != value))
				{
					this._JPY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GBP", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> GBP
		{
			get
			{
				return this._GBP;
			}
			set
			{
				if ((this._GBP != value))
				{
					this._GBP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CAD
		{
			get
			{
				return this._CAD;
			}
			set
			{
				if ((this._CAD != value))
				{
					this._CAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHF", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CHF
		{
			get
			{
				return this._CHF;
			}
			set
			{
				if ((this._CHF != value))
				{
					this._CHF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> INR
		{
			get
			{
				return this._INR;
			}
			set
			{
				if ((this._INR != value))
				{
					this._INR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CNY
		{
			get
			{
				return this._CNY;
			}
			set
			{
				if ((this._CNY != value))
				{
					this._CNY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRY", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> TRY
		{
			get
			{
				return this._TRY;
			}
			set
			{
				if ((this._TRY != value))
				{
					this._TRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> SAR
		{
			get
			{
				return this._SAR;
			}
			set
			{
				if ((this._SAR != value))
				{
					this._SAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> IDR
		{
			get
			{
				return this._IDR;
			}
			set
			{
				if ((this._IDR != value))
				{
					this._IDR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AED", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AED
		{
			get
			{
				return this._AED;
			}
			set
			{
				if ((this._AED != value))
				{
					this._AED = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THB", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> THB
		{
			get
			{
				return this._THB;
			}
			set
			{
				if ((this._THB != value))
				{
					this._THB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VND", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> VND
		{
			get
			{
				return this._VND;
			}
			set
			{
				if ((this._VND != value))
				{
					this._VND = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EGP", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> EGP
		{
			get
			{
				return this._EGP;
			}
			set
			{
				if ((this._EGP != value))
				{
					this._EGP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KRW", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> KRW
		{
			get
			{
				return this._KRW;
			}
			set
			{
				if ((this._KRW != value))
				{
					this._KRW = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUB", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> RUB
		{
			get
			{
				return this._RUB;
			}
			set
			{
				if ((this._RUB != value))
				{
					this._RUB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAR", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> ZAR
		{
			get
			{
				return this._ZAR;
			}
			set
			{
				if ((this._ZAR != value))
				{
					this._ZAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AUD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AUD
		{
			get
			{
				return this._AUD;
			}
			set
			{
				if ((this._AUD != value))
				{
					this._AUD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G5", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> G5
		{
			get
			{
				return this._G5;
			}
			set
			{
				if ((this._G5 != value))
				{
					this._G5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROD", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> PROD
		{
			get
			{
				return this._PROD;
			}
			set
			{
				if ((this._PROD != value))
				{
					this._PROD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONS", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> CONS
		{
			get
			{
				return this._CONS;
			}
			set
			{
				if ((this._CONS != value))
				{
					this._CONS = value;
				}
			}
		}
	}
	
	public partial class AvgWeekDayResult
	{
		
		private System.Nullable<long> _Id;
		
		private System.Nullable<int> _WeekDayNum;
		
		private string _WeekDay;
		
		private System.Nullable<decimal> _AvgBuy;
		
		private System.Nullable<decimal> _AvgSell;
		
		public AvgWeekDayResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="BigInt")]
		public System.Nullable<long> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekDayNum", DbType="Int")]
		public System.Nullable<int> WeekDayNum
		{
			get
			{
				return this._WeekDayNum;
			}
			set
			{
				if ((this._WeekDayNum != value))
				{
					this._WeekDayNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WeekDay", DbType="NVarChar(30)")]
		public string WeekDay
		{
			get
			{
				return this._WeekDay;
			}
			set
			{
				if ((this._WeekDay != value))
				{
					this._WeekDay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgBuy", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AvgBuy
		{
			get
			{
				return this._AvgBuy;
			}
			set
			{
				if ((this._AvgBuy != value))
				{
					this._AvgBuy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgSell", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> AvgSell
		{
			get
			{
				return this._AvgSell;
			}
			set
			{
				if ((this._AvgSell != value))
				{
					this._AvgSell = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
